import os
import tweepy
from dotenv import load_dotenv
from chatbot import respond

load_dotenv()

# Retrieve Twitter authentication keys and secrets from .env file
CONSUMER_KEY = os.getenv('CONSUMER_KEY')
CONSUMER_SECRET = os.getenv('CONSUMER_SECRET')
ACCESS_KEY = os.getenv('ACCESS_KEY')
ACCESS_SECRET = os.getenv('ACCESS_SECRET')

auth = tweepy.OAuthHandler(CONSUMER_KEY, CONSUMER_SECRET)
auth.set_access_token(ACCESS_KEY, ACCESS_SECRET)
api = tweepy.API(auth)

# I use last_seen_id so that Tweepy only return statuses more recent than the specified ID
FILE_NAME = 'last_seen_id.txt'


def retrieve_last_seen_id(file_name):
    """Retrieve last_seen_id from last_seen_id.txt"""
    f_read = open(file_name, 'r')
    last_seen_id = int(f_read.read().strip())
    f_read.close()
    return last_seen_id


def store_last_seen_id(last_seen_id, file_name):
    """Store last_seen_id to last_seen_id.txt"""
    f_write = open(file_name, 'w')
    f_write.write(str(last_seen_id))
    f_write.close()


def reply_tweets():
    """
    Pull mentions that are more recent than last_seen_id.
    Reply to the tweets with responses generated by the model.
    """
    last_seen_id = retrieve_last_seen_id(FILE_NAME)

    # NOTE: Use tweet_mode='extended' below to show uncut long tweets.
    # since_id – Returns only statuses with an ID more recent than the specified ID.
    mentions = api.mentions_timeline(since_id=last_seen_id,
                                     tweet_mode='extended')

    for mention in reversed(mentions):
        last_seen_id = mention.id
        request = " ".join(mention.full_text.split()[1:])
        print(request)
        store_last_seen_id(last_seen_id, FILE_NAME)

        chatbot_response = " ".join(respond(f'''{request}''').split()[:-1])

        api.update_status(status='@' + mention.user.screen_name + ' ' + chatbot_response,
                          in_reply_to_status_id=mention.id)


reply_tweets()