# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: chatbot
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

provider:
  name: aws
  runtime: python3.8
  region: us-east-2
  memorySize: 10240
  timeout: 300
# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
        - "dynamodb:*"
      Resource: "*"


# you can add packaging information here
#package:
##  individually: true
##  include:
##    - include-me.py
##    - include-me-dir/**
#  exclude:
#    - node_modules/**
#    - package.json
#    - package-log.json
#    - cache/**
#    - test/**
#    - __pycache__/**
#    - .pytest_cache/**
#    - raw/**
#    - venv/**
#    - .git/**
#    - .DS_Store
#    - .pyc
#    - /external/*
#    - /tensorflow/contrib/*
#    - /tensorflow/include/unsupported/*.

functions:
  chatbot:
#    handler: handler.reply_tweets
#    memorySize: 10240
#    timeout: 300
    image: 028050957209.dkr.ecr.us-east-2.amazonaws.com/chatbot-lambda@sha256:b86793ee3dd94c6ca7a85ba6d112e401b76bf8d47cfe2e1a996821bc1435178d
    events:
      - schedule: cron(0 9 ? * * *)

#custom:
#  pythonRequirements:
#    dockerizePip: true
#    slim: true
#    zip: true
#    strip: false
#    useDownloadCache: true
#    useStaticCache: true
#    cacheLocation: "./cache"
#    noDeploy:
#      - boto3
#      - botocore
#      - docutils
#      - jmespath
#      - pip
#      - python-dateutil
#      - s3transfer
#      - setuptools
#      - six
#      - tensorboard

#  webpack:
#    config: ./path/to/config/file.js
#    series: true # run Webpack in series, useful for large projects. Defaults to false.

#plugins:
#  - serverless-python-requirements
